ssh_host_ed25519_key:
    public: ENC[AES256_GCM,data:4tAhCQY0e0Ofw6irnu9GmQ646IUBiTiNmfFqD4ZoESc+ckzjpYPJFvsCXTYVkEf4S6pTK+TrCedIhU8mMxvDpII0RZtRZDdlJv+EcQ5SHz0=,iv:IreTEZvVjm++TepyYpYAjNHpAXlejBWUP9S748khHVU=,tag:c3C+YGC0fGq+85KuYSL+zA==,type:str]
    private: ENC[AES256_GCM,data:Qn2PlYFI8L8YwOJzYVGo3cwktevB1Th6kFpfRyhkp87+73YmryGDndKQezP2xBekl3Visih4jRadzYlmpoAgtYZXyUFIHpK8spAwyo6zBLENLFbhCpT0vNSW1SysDTg0cYxwhWlEIp8rnSWdm0VqPi57pX3kPrmb6tpVNREn+seoYOv9XSESyHDGg1muU3L2sOzSqWIGWYhPB2DYfe11+gcDuKWxWi/mK/BLWos42dFFaESfpFfIOF0mIBvZQ/xahM+UMeqUxeyzSDP0eRHmXCPRf1fNbK7IfAoHdtOgO8uA+5l8+ADGlpEFQCBNG461vzEfO3epwCRsMEJQo7/k0JCneYSATic9AslIqYHvEp8qsEqCdT706EqyaBr+xvzXqpiB16PgshMnLOXyE1ZZI/Aa6PjH3C6q97AkFlTKFHB4EXPdQz8fPOKOYz1VHvNHVOo6MnJ9MmzMSw7tpa1vc7rgz/qIBNVrXAxzWWgTMtXJRUggZKsy2lOh4vS5nYycE/aM,iv:qnLKUt7UxLW2DmBBDQyvtFr4j0L2VPGwVxAHro63Ha0=,tag:kiyKwQgutUJMPAo6PI++Fw==,type:str]
hashed_user_passwords:
    root: ENC[AES256_GCM,data:pp3Y5OCbs7cE4gICLhZTr40Lvgh3PLRXRi6+ptEZzWiih4E2CYVgI7nyVPkv0DcyMmXZMBqOgUNO52Kv,iv:WNGFBZdJSoN8BQDmendADOR91PlbI9bhomg3TFb1xzY=,tag:TAYXIIKxEySfKLEI4FjByQ==,type:str]
sops:
    age:
        - recipient: age1mpsgu5eywvyxxu0fsp4v5gfz5yrnusmr6u5rdjguwy6hwwgs4ycsv6dm35
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMlk2d2pKM3J2QkNMSEFG
            VjJaTW50L0xFRHhCbEpnYTBGaHV4a2ZWVUYwCkVtRnRkT1pXVEdOUzlOK0VrNFFv
            UGZSWlVZZG1zUlRwTFJrSlc4cGQ4NFEKLS0tIGdrUTRPNFdpSm9NbUd0cEJMWlJP
            R2F3Vld4clVQWHpDOE5IWTc3MVVmc28Kmt1kgLG3SjmvRZNp1S3cF+G0sllbOxyv
            51BQAcglG3fKwwxnaTTKHG61sCTxxi0XyoxfGrUsbfpQcJDA/jHLJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T06:47:55Z"
    mac: ENC[AES256_GCM,data:bmbuDQukgCA8Gb4NZqpc0nvVIkXYZhfJcg55fAZBL+iVvqd3axK6k5LWMqYN/xCKxnDOzfFxNkHCTGAlPwTd3PDXN5SXUHN7B5sRMJpcNJ14Bc9XtAjT3HL3a3DuHj74avQ6r47IxIRU2xgNjEanY/4UO48DMVmh1AQsDpxiuHc=,iv:IKyppoqViZBqoT+bknc5G26JP9UpBC7N0OCcNddWSm0=,tag:nYbTz2/dsJ1ooSsGndKdFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
