password: ENC[AES256_GCM,data:AEFosdd4,iv:mh+7zhDlr+RDs3YopS5dy8vVW+kiEhDvJ6LjjkInDxU=,tag:JsqYSctrP4iRT2meo/DKVg==,type:int]
sops:
    age:
        - recipient: age1v35c8pstlm756dj5dsyu0qf7em8vcj4hsxc7cl26n43cmrzgyfyq0zj66v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SUhMVzVIbk9hWExtRjVm
            dlFLY2poT2oxUnFkYTBFT3RmRVlTODRISG5rCjUyZy93bTdadTYzU0dyZTcxS1hO
            anFHay9RL1FxeE1EQ0lWUHNtekQ5U1kKLS0tIHlCVWtVVXM0VDFoMWNqc3NaS29X
            T0FicmpwdEg2c0U1bVBHTGlCZkhWKzQKJ0kWIs9Sr2rz1m7QaVMNeWOkwIu8APlV
            cb+daTaQqxUvXHMaubJczy4xPZxQzXkhV6wgFTYNjPVwWN980Toi8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14lcrpxnt4wyswqppf9t4xvqymnacvckkhsq4hw8gwx2ztx64rass7a0nj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRkxEK0JrNjhqWDR5ZU5W
            OTNsQk44d0RwYVB4Z1krVG5HSzBvaVNhVUZRCnpERnZnNytONTMyUnBybDJFWmND
            SGlTSlpXMVg0Y2NzUURKK2lWNkFUTE0KLS0tIEd3SkM4Vm9ENTRJbkdGSnptVHdE
            Z1hGb28vWkJKUzBFTmRtd0JYQmVVNjAKVZa8pqsUFZwVTDAPqUHURRiDwVlmliFq
            v0QmC4NZP+U/OUh6M96a4TCdH9R04rDk2DfxQc6bZs4Ra+ZDiZgVWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T08:18:21Z"
    mac: ENC[AES256_GCM,data:UwItjBFt4ciJeL8hJO9++8LxRuBeEOQrzLO/dQ1zsR5rIiWR7BnVb/+ztFNLMCj5dKDszoT14/QLK5Q1zKrJEIK1ZzK6xscSSLKctrfz+8DH5lzD+NjJknmtmE5AKJqB3FD6Fu/UStLAxJo14ilmRw7Kj/sSo+It2YWzHt59joA=,iv:QPJEHBHxNeudU16dfRn+u1Q97DPhLM3r9UiJTLQ5OMQ=,tag:HxM+4paU07VvID9340pFTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
