wow: ENC[AES256_GCM,data:H89f0A==,iv:1JMI3Zj94U5aJcRxt7OpFE2VXkvKLwWh4ZlscH7l2yc=,tag:cFhm9Fy2Zm9IebFoca4dSQ==,type:bool]
sops:
    age:
        - recipient: age1v35c8pstlm756dj5dsyu0qf7em8vcj4hsxc7cl26n43cmrzgyfyq0zj66v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBILzdmeHhZSnVYUXBuTnZP
            dElDZnVSZzFhZjRyNXVUN2pmTVNBUm5RNFdrCldwa0pQSTZPZ3E3dGZHZkpmZms5
            RytRTVZBa0NwcE53cDRwRFVndWhRZncKLS0tIFIrOFdZN3dJNU5xUXdRMHZXUGkz
            U0ZGVTQ5azZsRHM3dDlEa01xaUNQbmMKZjL+DSdU9p1MMszM+FnePJO8yS8fga6B
            JTOZguqhgnIV7iI/GRfD2KSzrGD9U//KpK1l9eDt0zTusqF4eCXBjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14lcrpxnt4wyswqppf9t4xvqymnacvckkhsq4hw8gwx2ztx64rass7a0nj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzalNCTzIrVWFBcEZtOEMw
            V1JRSlF5ZWFicTRxRFJuR1BWdXRBeGJzZ3hRCjRBdTJlQ1YvZWxYdmVtZHNrOVFE
            V21HcVYvTjRjNC9LdGRpOWhrVU5IbjAKLS0tIEtDMDJTYTVtekdjb0JsSXk4U3Zi
            S3N4VG1MbXdPbFB3SU01RmRpRTBnWXcKZKTpi2zIW1jcMOwKl7X3wnKFR9567jaH
            5Ak8sQGS/m++ENVfVykTVJB2LYKDzGkJLiOO5J6E8Y6Xes9jHvZAzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T02:46:38Z"
    mac: ENC[AES256_GCM,data:upJIdvoJYmThopZHr5l77sStWTdZLNaXHeJp7pNYNkuuBvK+lQ3JhXeUxN/kHor/cr7dDBWiXobSDbktrn5/S7zLOrB/ctKIlaPvjhpARkCbNs31w+6m7f3xD8tg9ABNY5c2M7Y30gYeEoMG5mnbN657APD/g0H8fFhBdvkjxgU=,iv:mka+e7/wv+BDLWiPvZKhu6BXiFufeJDumBYeOZK1AoU=,tag:av2EIfreeeo5DwmYAHQH8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
