ssh_id_ed25519_keys:
    suu@mochi:
        public: ENC[AES256_GCM,data:ddTcHWu/RcIx2GkDZnoehKx8gjmV8X+u1vYEWOWTdOa4gWb11yzJQyTjEmVturR2KXmxjPZQjuBYRmQ9GcevtzbkAEWttgHofeO9Auwqdz6328BCVf8ouwzF,iv:NaiH5CUIMWCGfl4TnQThvxf7rSZzGd4+daaRqstfyEE=,tag:cM3QE83yOnJZTlOMDjDrzw==,type:str]
        private: ENC[AES256_GCM,data:rGIDYajDDj+2hgKyFbS/RCmEezjuHTQQ7iYnovhM0JsvSkpSYd3v8GUpotu4iDOFxoooCO9bxTUt2IANC3p8BZKzbvDbmPa8iyJddqRjzmp7X8VjUci8ZrckdQNl2p4vNQUxIgDpqSg+jr1BfYHSfgsR1gh2tiD7TQPh/mAozL91yPOchMAwaU/cvJHs8oGBai6ubp7U3hHN/nef0ZyO+ZahKDv9JW5Js2IWwvpivPRqMvOXBnyVpT8nzSr6thIMNWfRW4B/BPVIB50yAODEfJq6vOWVUsoOF6BVHD3k+iWYi3zSHwfnxljwnZwauL/ktMm2FJJb6DZVi0rQ64S/P8EEVHWmaGJgPOLAxdZxqkOU/yOcVXT+bhLhbH9LDmDZ180EzCgLbkXMCVupQFBZ6PotBAsOVk7yo/0zGLhWspLGd3NVTbX5qdhPopnMlB+GHWHb2LpLSUt7rxx3KOLjYxUFps0xZO27kFHbgWW++Vo/3Ob1LbdsAztddM4AqpmBZGuzJ9cRTBf39lujJ2U2,iv:O5C3vJOZnwz84Slp0B7V59KjDxKzErhbQUPREsWcKg8=,tag:UZZygBKLo49gIZqYN4GrPw==,type:str]
    suu@taco:
        public: ENC[AES256_GCM,data:VH/LHK+wEJ6ltHsK6wsKiVquNYAhVqHbqdmWAgCWU6/GuUyxUTNziDSNbmFgcIgkzataSR6wYsTstVW+CWxXKhaEzf78Sdn/1VFAAYNua8A7bJjAYQbLfe4=,iv:o6wIlxKZDzZiL4XS7fpt0RrgX7j9Hjmw6oJAt5Q40QI=,tag:hqiMFNsRKc6cXV7Ep1RS4Q==,type:str]
        private: ENC[AES256_GCM,data:EvqXMBjrWD7e6ndtrLXd8wo6b3sMrK/0LBMVVaaTtqHdVz4HL1x9j9rFtzYDSValUKoHPID6yzeyEdq0NWZaoew4GuKLdNBQfxamNYdNO7ZMiOcgRFBLNMRXgVdDwkmt3ed/aKgL4HoMBzk1vVmgJQezB1Qy/djF0fbeonRb7yynnYmUw3qeezzKml2Vuy+hnS3Lq1hx9rlaYjeLUB2Q6tslKHn6GX/xlyBl4Ai6bI+sNFoTWrMFEoWflGToB7FHjvB16BUDKrQQX+7c6AdG5l2f0rlDNcjXEsEtpXAHB01LS+NFhZPNOp2JSYcBzWghua+w8wIu2Rn93snqynXBtPZaG28vLJUQ5E0v22XYqzbk36CROH9d2a3cpSx/erlWY9v/g59811g38Ja/GyXs6ry1Eoz8S/MHZsDcb4kP/RWeWUT+sTiELdV23CIknTG47+9i90oBgAlqE3aSM8exNGdbeowp41wh6akRBWsCXahB7YeTbeqR+0EnG2X0Tsaf3FVDeMC/LQNlIb7dhIVhyycMv17rYdfxmXbfVCqbCB5Z/jE=,iv:VWxTeMtMLZab/HpGiMPQN79TuLZx6Yj9JAgpdwh0cEs=,tag:tlVNf0E5jBtKVb9ocTG9rw==,type:str]
ssh_id_rsa_keys: null
wakatime:
    api_key: ENC[AES256_GCM,data:BN9BR8zv60h0h3QPKV4UR88GGWBOMuBHkyx9RydAEHSY3o04kX38X0I=,iv:j4bY6UhK+BfDYmmhajIUwI35C4EdF/OVUPXrVcF1abU=,tag:x6KtitWDrKo70XQn2B/neA==,type:str]
sops:
    age:
        - recipient: age1v35c8pstlm756dj5dsyu0qf7em8vcj4hsxc7cl26n43cmrzgyfyq0zj66v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTGVPdDZHVTlETTZjeHY1
            ZUx4MGR1aEJtU3VtTFN6a01ua2JIMDk1R0VZCmlaNHk1VHBkTUZITVdsVkxKU3B5
            VXhRM3BHNVp5a29Bd2hiUytLc1VMMkEKLS0tIHI1K2xyNkNHdG9OcnBPVjRjZzZ4
            UGxhaTFJd3BhanhMMk1FN2NIZGJyVmcK7f8u//YlqbmRMNFUfDV6wBdDktQ/t1oZ
            7HgQiKeUNChI4YUyd20ODc6888xMCQUeJ+GHnaSl8za4qlvUrGbdpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T20:47:25Z"
    mac: ENC[AES256_GCM,data:u+Q7uqiwCBz4WYE4eBBqNCeLrUcp4kl6RBcmwQJNc4KNSPOP0cQkV2ssG9PzKeOmKRfQ5GseLWSseHA6ZKB+82lp6joLf8HW/Xb0TXiCLJ3paaNPM0rB9LhgtYveg5++zccrh7SQFV0RuNllQDjsqwS1hBvucQWqGuojL1acBiE=,iv:RAcM8DHaojV1f7SUYbZfJ+syrJbzhzWuALKGRJ+8YMs=,tag:xM/nuEsf8ud68aApZ6hAnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
