use_default_settings: true

server:
  image_proxy: true

ui:
  query_in_title: true
  hotkeys: vim

search:
  favicon_resolver: duckduckgo
  formats:
    - html
    - json

engines:
  - name: bing
    disabled: false

  - name: yahoo
    disabled: false
